// Copyright (C) 2010-2014 Joshua Boyce.
// See the file COPYING for copying permission.

#pragma once

namespace divinity
{
enum Talent
{
  Talent_ItemMovement = 0x1,
  Talent_ItemCreation = 0x2,
  Talent_Flanking = 0x3,
  Talent_AttackOfOpportunity = 0x4,
  Talent_Backstab = 0x5,
  Talent_Trade = 0x6,
  Talent_Lockpick = 0x7,
  Talent_ChanceToHitRanged = 0x8,
  Talent_ChanceToHitMelee = 0x9,
  Talent_Damage = 0xA,
  Talent_ActionPoints = 0xB,
  Talent_ActionPoints2 = 0xC,
  Talent_Criticals = 0xD,
  Talent_IncreasedArmor = 0xE,
  Talent_Sight = 0xF,
  Talent_ResistFear = 0x10,
  Talent_ResistKnockdown = 0x11,
  Talent_ResistStun = 0x12,
  Talent_ResistPoison = 0x13,
  Talent_ResistSilence = 0x14,
  Talent_ResistDead = 0x15,
  Talent_Carry = 0x16,
  Talent_Throwing = 0x17,
  Talent_Repair = 0x18,
  Talent_ExpGain = 0x19,
  Talent_ExtraStatPoints = 0x1A,
  Talent_ExtraSkillPoints = 0x1B,
  Talent_Durability = 0x1C,
  Talent_Awareness = 0x1D,
  Talent_Vitality = 0x1E,
  Talent_FireSpells = 0x1F,
  Talent_WaterSpells = 0x20,
  Talent_AirSpells = 0x21,
  Talent_EarthSpells = 0x22,
  Talent_Charm = 0x23,
  Talent_Intimidate = 0x24,
  Talent_Reason = 0x25,
  Talent_Luck = 0x26,
  Talent_Initiative = 0x27,
  Talent_InventoryAccess = 0x28,
  Talent_AvoidDetection = 0x29,
  Talent_AnimalEmpathy = 0x2A,
  Talent_Escapist = 0x2B,
  Talent_StandYourGround = 0x2C,
  Talent_SurpriseAttack = 0x2D,
  Talent_LightStep = 0x2E,
  Talent_ResurrectToFullHealth = 0x2F,
  Talent_Scientist = 0x30,
  Talent_Raistlin = 0x31,
  Talent_MrKnowItAll = 0x32,
  Talent_WhatARush = 0x33,
  Talent_FaroutDude = 0x34,
  Talent_Leech = 0x35,
  Talent_ElementalAffinity = 0x36,
  Talent_FiveStarRestaurant = 0x37,
  Talent_Bully = 0x38,
  Talent_ElementalRanger = 0x39,
  Talent_LightningRod = 0x3A,
  Talent_Politician = 0x3B,
  Talent_WeatherProof = 0x3C,
  Talent_LoneWolf = 0x3D,
  Talent_Zombie = 0x3E,
  Talent_Demon = 0x3F,
  Talent_IceKing = 0x40,
  Talent_Courageous = 0x41,
  Talent_GoldenMage = 0x42,
  Talent_WalkItOff = 0x43,
  Talent_FolkDancer = 0x44,
  Talent_SpillNoBlood = 0x45,
  Talent_Stench = 0x46,
  Talent_Kickstarter = 0x47,
  Talent_WarriorLoreNaturalArmor = 0x48,
  Talent_WarriorLoreNaturalHealth = 0x49,
  Talent_WarriorLoreNaturalResistance = 0x4A,
  Talent_RangerLoreArrowRecover = 0x4B,
  Talent_RangerLoreEvasionBonus = 0x4C,
  Talent_RangerLoreRangedAPBonus = 0x4D,
  Talent_RogueLoreDaggerAPBonus = 0x4E,
  Talent_RogueLoreDaggerBackStab = 0x4F,
  Talent_RogueLoreMovementBonus = 0x50,
  Talent_RogueLoreHoldResistance = 0x51,
  Talent_InvalidIdMaxValue = 0x52,
};
}
