ProcName = raw_input("Process name: ")
MyMem = PyHadesMem.MemoryMgr(ProcName)
Address = int(raw_input("Target address: "), 16)
MyRegion = PyHadesMem.Region(MyMem, Address)
print("")
print("GetBase: " + hex(MyRegion.GetBase()))
print("GetAllocBase: " + hex(MyRegion.GetAllocBase()))
print("GetAllocProtect: " + hex(MyRegion.GetAllocProtect()))
print("GetSize: " + hex(MyRegion.GetSize()))
print("GetState: " + hex(MyRegion.GetState()))
print("GetProtect: " + hex(MyRegion.GetProtect()))
print("GetType: " + hex(MyRegion.GetType()))
