ProcName = raw_input("Process name: ")
MyMem = PyHadesMem.MemoryMgr(ProcName)
ModName = raw_input("Module name: ")
MyMod = PyHadesMem.Module(MyMem, ModName)
print("")
print("Base: " + hex(MyMod.GetBase()))
print("Size: " + hex(MyMod.GetSize()))
print("Name: " + MyMod.GetName())
print("Path: " + MyMod.GetPath())
