name: MSBuild

on:
  push:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: actions/create-release@v1
      with:
        draft: true
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}

  build:
    needs: create_release
    runs-on: windows-latest
    strategy:
      matrix:
        toolset: [v142]
        configuration: [Debug, Release]
        platform: [Win32, x64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Fix udis86
      run: New-Item -ItemType SymbolicLink -Path "c:\python27" -Target $Env:pythonLocation

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild build\vs\hadesmem.sln -target:hadesmem /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=${{ matrix.toolset }}

    - name: Setup Artifact
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |	
        mkdir artifact
        mkdir artifact\lib
        copy build\vs\${{ matrix.configuration }}\${{ matrix.platform }}\*.lib artifact\lib
        xcopy /s /i include artifact\include
        xcopy /s /i deps\asmjit\asmjit\src\asmjit\*.h artifact\deps\asmjit\asmjit\src\asmjit
        xcopy /s /i deps\udis86\udis86\*.h artifact\deps\udis86\udis86
        xcopy /s /i deps\pugixml\pugixml\src\*.?pp artifact\deps\pugixml\pugixml\src
        
    - uses: actions/upload-artifact@v2
      name: Upload Artifacts
      with:	
        name: hadesmem-${{ matrix.toolset }}-${{ matrix.configuration }}-${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/**/*
        retention-days: 8

    - uses: softprops/action-gh-release@v1
      name: Upload assets to release
      with:
        files: artifact/**/*

  release:
    needs: build
    runs-on: ubuntu-latest
    #on:
    #  label:
    #    types: [created]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
    - name: Debug
      run: ls -R