name: MSBuild

on:
  push:
  schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        toolset: [v142]
        configuration: [Debug, Release]
        platform: [Win32, x64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 2.7

    - name: Fix udis86
      run: New-Item -ItemType SymbolicLink -Path "c:\python27" -Target $Env:pythonLocation

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild build\vs\hadesmem.sln -target:hadesmem /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=${{ matrix.toolset }}

    - name: Setup Artifact
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |	
        mkdir artifact
        mkdir artifact\lib
        copy build\vs\${{ matrix.configuration }}\${{ matrix.platform }}\*.lib artifact\lib
        xcopy /s /i include artifact\include
        xcopy /s /i deps\asmjit\asmjit\src\asmjit\*.h artifact\deps\asmjit\asmjit\src\asmjit
        xcopy /s /i deps\udis86\udis86\*.h artifact\deps\udis86\udis86
        xcopy /s /i deps\pugixml\pugixml\src\*.?pp artifact\deps\pugixml\pugixml\src
        
    - uses: actions/upload-artifact@v2
      with:	
        name: hadesmem-${{ matrix.toolset }}-${{ matrix.configuration }}-${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/**/*
        retention-days: 8
